{% set name = "mahotas" %}
{% set version = "1.4.13" %}
{% set sha256 = "a78dfe15045a20a0d9e01538b80f874580cd3525ae3eaa2c83ced51eb455879c" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script:
    # C++ code is not yet C++17 compatible. So use C++14 for now.
    # xref: https://github.com/luispedro/mahotas/issues/146
    - export CXXFLAGS="${CXXFLAGS} -std=c++14"  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mahotas-features = mahotas.features_cli:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - scipy
    - pillow

  imports:
    - mahotas

  commands:
    - mahotas-features --help

about:
  home: https://mahotas.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: COPYING

  summary: 'Mahotas: Computer Vision Library'
  description: |
    Mahotas is a library of fast computer vision algorithms
    (all implemented in C++) operating over numpy arrays.

  doc_url: https://mahotas.readthedocs.io/
  dev_url: https://github.com/luispedro/mahotas

extra:
  recipe-maintainers:
    - jakirkham
    - luispedro
