{% set name = "mahotas" %}
{% set version = "1.4.9" %}
{% set sha256 = "4c65f462a09fe19dea4ac7b630039478e9691126e430ace485e965635e535f71" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - mahotas-features = mahotas.features_cli:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - nose
    - scipy
    - pillow

  imports:
    - mahotas

  commands:
    - mahotas-features --help

about:
  home: https://mahotas.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: COPYING

  summary: "Mahotas: Computer Vision Library"
  description: |
    Mahotas is a library of fast computer vision algorithms
    (all implemented in C++) operating over numpy arrays.

  doc_url: https://mahotas.readthedocs.io/
  dev_url: https://github.com/luispedro/mahotas

extra:
  recipe-maintainers:
    - jakirkham
    - luispedro
