{% set name = "mahotas" %}
{% set version = "1.4.15" %}
{% set sha256 = "d79b1bb36c195543d5a1f0e171c8edf6a142184ac11177f90b5f0098ef86e07c" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mahotas-features = mahotas.features_cli:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  files:
    - run_testsuite.py
  requires:
    - python
    - pytest
    - scipy
    - pillow
  imports:
    - mahotas
  commands:
    - mahotas-features --help
    - python run_testsuite.py

about:
  home: https://mahotas.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: COPYING

  summary: 'Mahotas: Computer Vision Library'
  description: |
    Mahotas is a library of fast computer vision algorithms
    (all implemented in C++) operating over numpy arrays.

  doc_url: https://mahotas.readthedocs.io/
  dev_url: https://github.com/luispedro/mahotas

extra:
  recipe-maintainers:
    - jakirkham
    - luispedro
